### ISSUE TITLE
Cannot add the Client.txt file if the path to it does not contain 'Path of Exile'.

### ISSUE THREAD

**Issue by sozemego** [cedricdsc/poe-instant-messenger#9]
This seems to be the way it is programmed (SetupStepper.tsx:64), but at least I didn't install PoE in a standard directory. Perhaps this is not technically a bug, but to a casual user it might look like a bug.

**Comment by cedricdsc** [comment]
That was something I was afraid of people would report. I'll probably change it to check for 'Path of Exile' in the given folder and then use the implemented logic as of now if its true, else the given path will be used.

**Comment by sozemego** [comment]
What is the reason for this check? Is it just to make sure the user does not select the wrong file? If so, perhaps there is a way to validate the content of the file (not sure if there is a reliable content in the first few lines of the file).

**Comment by cedricdsc** [comment]
> What is the reason for this check? Is it just to make sure the user does not select the wrong file?

Exactly. I thought it would be need if the user can select any file in the directory and it still knows where the log file is. Not every user knows what 'log file' means. But I see the problem and will come up with a fix for this. Thanks for pointing that out!

**Comment by cedricdsc** [comment]
The software now asks for the game directory instead of the location of the log file. That should be a solid fix for everyone.
